language: php

sudo: required
dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

before_install:
  - sudo rm /etc/apt/sources.list.d/couchdb.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq libzmq3-dev libsodium-dev

before_script:
  - echo "extension = zmq.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && $TRAVIS_PHP_VERSION != "hhvm" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
